defaults: &defaults
  adapter: mysql2
  encoding: utf8
  reconnect: false  
  pool: 5
  username: "<%=Rails.application.secrets.database['username'] %>"
  password: "<%=Rails.application.secrets.database['password'] %>"
  localhost: localhost

development:
  <<: *defaults
  database: littlefire_development

test:
  <<: *defaults
  database: littlefire_test

production:
  <<: *defaults
  database: littlefire_production
  pool: 10